# Compose file for Neko <https://neko.m1k1o.net/>
#
# Copyright 2025 Miroslav Šedivý et. al. <https://github.com/m1k1o/neko/blob/eba9821/docker-compose.yaml>
# SPDX-License-Identifier: Apache-2.0
services:
  neko:
    image: "ghcr.io/m1k1o/neko/firefox:latest"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_DESKTOP_SCREEN: 1920x1080@30
      NEKO_MEMBER_MULTIUSER_USER_PASSWORD: neko
      NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: admin
      NEKO_WEBRTC_EPR: 52000-52100
      NEKO_WEBRTC_ICELITE: 1
