# REUSE licensing information association file
#
# References:
#
# * REUSE.toml | REUSE Specification – Version 3.2 | REUSE
#   https://reuse.software/spec-3.2/#reusetoml
#
# Copyright 2024 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0+

version = 1

[[annotations]]
path = [
    "*.README.md",
    "**/README.md",
    "screenshot.png"
]
SPDX-FileCopyrightText = '2025 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>'
SPDX-License-Identifier = 'CC-BY-SA-4.0+'

[[annotations]]
path = [
    "logo.png"
]
SPDX-FileCopyrightText = "2025 This is a remix of the original Neko project logo <https://neko.m1k1o.net/img/logo.png>"
SPDX-License-Identifier = 'Apache-2.0'
